---
title: "Whats in your DHIS2?"
version: "0.90"
output: 

  html_document:
    css: custom.css
    # toc: TRUE
    # toc_float: TRUE
    toc_depth: 4
    code_folding: hide
    fig_caption: TRUE
    self_contained: TRUE
    # template: html_template.html 
    
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


source('dhis2_functions.R')


```

# {.tabset .tabset-fade}
 
## Login

```{r credentials, echo=FALSE}
inputPanel(
    
  textInput("baseurl", label = "DHIS2 URL:", "https://play.dhis2.org/2.28/" ),
  
  textInput("username", label = "User name:", "admin"),
  
  passwordInput("password", label = "Password:", "district")
)

baseurl = reactive({
        # if url is from login or dashboard url, trimto get baseurl
       baseurl = gsub( "dhis-web-commons/security/login.action"  , "" , input$baseurl , 
                       fixed = TRUE  ) 
       baseurl = gsub( "dhis-web-dashboard-integration/index.html"  , "" , baseurl , 
                       fixed = TRUE  ) 
       
})

login = reactive({ 
    
      # purrr::possibly(
        loginDHIS2( baseurl() , input$username, input$password) 
      #   otherwise = FALSE
      # )

    })

```


System Information:

```{r}

system.info = reactive({
 
     if ( login() ){
        # there are a couple forms of metadata in the api.  This code tests the format, then gets metadata
        # if available, use resources method
       
        url = paste0( baseurl() , "api/system/info" )
        getInfo = GET( url )
        getInfo.content =  content( getInfo , "text")
        info =   jsonlite::fromJSON( getInfo.content ) %>% 
          as_tibble() %>%
          filter( row_number() == 1 ) %>%
          select( version, buildTime  ,
                  lastAnalyticsTableSuccess ,
                  intervalSinceLastAnalyticsTableSuccess ,
                  lastAnalyticsTableRuntime ,
                  calendar, dateFormat )
     }
}) 

conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                          tags$div("Loading...",id="loadmessage")
         ) 

renderTable( 
    
    system.info() 
    , striped = TRUE , spacing = 's'

)

```

##  Available Metadata 

- The href column lists a url (e.g. https://play.dhis2.org/2.28/api/categories) that will returns a short list of information for each attribute. 

- Appending '?fields=:all&paging=false' (e.g. https://play.dhis2.org/2.28/api/categories?fields=:all&paging=false) to the url will provide all available information for that attribute. 

```{r resources  }
resources = reactive({
 
     if ( login() ){
        # there are a couple forms of metadata in the api.  This code tests the format, then gets metadata
        # if available, use resources method
       
        url = paste0( baseurl() , "api" )
        resources =  get( url )[['resources']]  %>% as_tibble() %>%
          arrange( displayName )
     }
}) 

conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                          tags$div("Loading...",id="loadmessage")
         ) 

renderTable( 
    
    resources() %>% select( displayName, href ) %>% rename( Attribute = displayName ),
    striped = TRUE , spacing = 's' 

)
```

## All Data Elements 

```{r all_data_elements }

conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                          tags$div("Loading...",id="loadmessage")
         ) 


dataElements = reactive({
        
    if (  login() ){
    
    # there are a couple forms of metadata in the api.  This code tests the format, then gets metadata
    # if available, use resources method
    url<-paste0( input$baseurl,"api/dataElements.json?fields=:all&paging=false")
    cols = c( 'id', 'name', 'shortName' , 'displayName', 'displayShortName' , 'categoryCombo' ,
              'zeroIsSignificant' )
    dataElements =  get( url )[[1]] %>% select( !!cols ) 
    
    } else { "Unable to login to server" }
}) 

dataElementGroups = reactive({
        
    if (  login() ){
    
    # there are a couple forms of metadata in the api.  This code tests the format, then gets metadata
    # if available, use resources method
    url<-paste0( input$baseurl,"api/dataElementGroups.json?fields=:all&paging=false")
    cols = c( 'id', 'name' , 'dataElements' )
    dataElementGroups =  get( url )[[1]] %>% select( !!cols ) %>%
      rename( dataElementGroups.id = id , dataElementGroup = name )
    
    deg = map_df( 1:length( dataElementGroups$dataElementGroup) , 
                  ~merge( dataElementGroups[ .x, 1:2] ,
                              dataElementGroups$dataElements[[.x]] , all = T)
                          ) %>%
      rename( dataElement.id = id)
    
    return( deg )
    
    } else { "Unable to login to server" }
}) 


dataSets = reactive({
        
    if (  login() ){
    
    # if available, use resources method
    url<-paste0( input$baseurl,"api/dataSets.json?fields=:all&paging=false")
    cols = c( 'id', 'name' , 'dataSetElements' )
    dataSets =  get( url )[[1]] %>% select( !!cols ) %>% 
      rename( dataSet.id = id, dataSet = name )
    
    } else { "Unable to login to server" }
}) 


categoryCombos = reactive({
        
    if (  login() ){
    
    # if available, use resources method
    url<-paste0( input$baseurl,"api/categoryCombos.json?fields=:all&paging=false")
    cols = c( 'id', 'name'  )
    categoryCombos =  get( url )[[1]] %>% select( !!cols ) %>% 
      rename( categoryCombo.id = id, categoryCombo = name )
    
    } else { "Unable to login to server" }
}) 


de.rows = reactive({ 
  req( dataElements() )
  de = dataElements()
  de.rows = nrow(de)
  paste( 'There are', de.rows , 'data elements' ) 
  
  })

renderText( de.rows() )

ds.rows = reactive({ 
  req( dataSets() )
  ds = dataSets()
  ds.rows = nrow(ds)
  paste( 'There are', ds.rows , 'data sets (forms) ' ) 
  
  })

renderText( ds.rows() )

cc.rows = reactive({ 
  req( categoryCombos() )
  cc = categoryCombos()
  cc.rows = nrow(cc)
  paste( 'There are', cc.rows , 'categoryCombos ' ) 
  
  })

renderText( cc.rows() )


```

```{r all_dsde }

# download button
 downloadHandler(filename = function() { 
    return(paste('data_element_names', '.csv', sep=''))

 }, content = function(file) {
   write.csv( dataElements() , file)
 })


dataDictionary = reactive({
  req( dataElements() )
  req( dataSets() )
  req( categoryCombos() )
  req( dataElementGroups() )
  
  de = dataElements()
  ds = dataSets()
  cc = categoryCombos()
  deg = dataElementGroups()
  
  # create matrix of data elements within each dataset 
  # (info comes from dataset table, not data element table)
  
  dsde = map_df( 1:length( ds$dataSetElements), 
                 ~map_df( ds$dataSetElements[[.x]], 
                          ~as.matrix(.x) )) 
  
  dsde = dsde %>%
    rename( dataElement.id = dataElement ,
            dataSet.id = dataSet ,
            categoryCombo.id = categoryCombo ) %>%
    left_join( de %>% select( -categoryCombo ) ,
               by = c('dataElement.id' = 'id' )) %>%
    rename( dataElement = name ) %>%
    
    left_join( ds %>% select( dataSet.id, dataSet ) ,
               by = 'dataSet.id' ) %>%
    
    left_join( cc, by = 'categoryCombo.id'  ) %>%
 
    left_join( deg , by = 'dataElement.id' )  %>%
    
    select( dataSet, dataElement, categoryCombo , dataElementGroup , zeroIsSignificant , 
            dataSet.id, dataElement.id, categoryCombo.id , shortName , displayName, displayShortName )
    
  # For versions <2.6, need to add categoryCombo
  # if ( !'categoryCombo' %in% names(dsde) ){
  #   categoryCombos =  tibble(
  #     dataSet =ds$dataSet ,
  #     categoryCombo = ds$categoryCombo$id )
  # 
  #   dsde = dsde %>% inner_join( cc,  by = "dataSet")
  # }
  
  return( dsde )
  
  })

DT::renderDataTable( 
    
    dataDictionary()  
    # , striped = TRUE , spacing = 's' 

)
```

## Malaria-relevant Data Elements 

```{r select_data_elements , eval=FALSE}

conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                          tags$div("Loading...",id="loadmessage")
         ) 


dataElements = reactive({
        
    if (  login() ){
    
    # there are a couple forms of metadata in the api.  This code tests the format, then gets metadata
    # if available, use resources method
    url<-paste0( input$baseurl,"api/dataElements.json?fields=:all&paging=false")
    cols = c( 'id', 'name', 'shortName' , 'displayName', 'displayShortName' , 'categoryCombo'  )
    dataElements =  get( url )[[1]] %>% select( !!cols ) 
    
    } else { "Unable to login to server" }
}) 

de.rows = reactive({ 
  req( dataElements() )
  de = dataElements()
  de.rows = nrow(de)
  paste( 'There are', de.rows , 'data elements' ) 
  
  })

 
renderText( de.rows() )


# download button
 downloadHandler(filename = function() { 
    return(paste('data_element_names', '.csv', sep=''))

 }, content = function(file) {
   write.csv( dataElements() , file)
 })


renderTable( 
    
    dataElements()  ,
    striped = TRUE , spacing = 's' 

)
```
